baseURL = "https://loix-me.netlify.com"
title = "Sébastien Loix"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Front-end engineer"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = [
    "vendors/photoswipe/photoswipe.css",
    "vendors/photoswipe/default-skin/default-skin.css"
]
customJS = [
]

gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Sébastien Loix"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "sebastian@loix.me"
github = "sebelga"
linkedin = "sloix"

[params.social.config]
platforms = ["github","email","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true
hardLineBreak = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.es]
lang = "es"
languageName = "Español"
weight = 2
