[build]
  publish = "public"
  command = "npm run build:draft"

[context.production]
  command = "npm run build:prod"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"
